version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: vod_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: vod_db
    restart: always
    networks:
      - vod_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: vod_rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    networks:
      - vod_network

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: vod_api
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: mongodb://mongodb:27017/vod_db
      RABBITMQ_URI: amqp://user:password@rabbitmq:5672
      PORT: 3000
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - mongodb
      - rabbitmq
    restart: on-failure
    networks:
      - vod_network

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    container_name: vod_worker
    environment:
      MONGODB_URI: mongodb://mongodb:27017/vod_db
      RABBITMQ_URI: amqp://user:password@rabbitmq:5672
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - mongodb
      - rabbitmq
    restart: on-failure
    networks:
      - vod_network

volumes:
  mongo_data:
  rabbitmq_data:

networks:
  vod_network:
